/*
   Copyright 2023 Prahlad Yeri

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */


drop table if exists projects;
drop table if exists milestones;
drop table if exists tasks;
drop table if exists timesheet;
drop table if exists notes;
drop table if exists mindmaps;
drop table if exists mcq;


create table projects (
	id integer primary key,
	status text, -- (Pending/WIP/Complete)
	name text,
	category text, -- (Work/Study/Other)
	tags text, -- (Tech/PHP/Python)
	start_date datetime,
	end_date datetime,
	notes text
);

create table milestones (
	id integer primary key,
	project_id int,
	name text,
	status text,
	tags text,
	foreign key (project_id) references projects(id)
);

create table tasks (
	id integer primary key,
	milestone_id int,
	name text,
	status text,
	-- category text, -- (study/work/writing/etc.)
	tags text,
	weekly_hrs int, -- no. of hours to be spend on this task each week.
	notes text,
	foreign key (milestone_id) references milestones(id)
);

create table timesheet (
	id integer primary key,
	task_id int,
	fdate datetime,
	tdate datetime,
	notes text,
	foreign key (task_id) references tasks(id)
);

create table mindmaps (
	id integer primary key,
	parent_id int, -- parent item's id or null in case of top level
	status text, -- Pending/WIP/Complete
	name text, -- topic name
	tags text,
	links text,
	notes int,
	foreign key (parent_id) references mindmaps (id)
);

create table notes (
	id integer primary key,
	status text, -- Pending/WIP/Complete
	topic text,
	notes text,
	due_date datetime -- for reminder, in case note is about an event. 
);
	
-- mcq @todo

--insert default rows
insert into projects(id, status, name, category, tags, start_date, end_date, notes) values (1, 'WIP', 'Default', 'Study', 'default,auto,programming', date('now'), date('now', '+2 months'), 'Default project auto generated by SimplePMS');